insert into public.products (
  slug,
  title,
  tagline,
  description,
  seller_display_name,
  seller_handle,
  price_cents,
  currency_code,
  hero_image_url,
  sale_end_time,
  drop_label,
  tag_list,
  sort_rank
)
values
  (
    'obsidian-runner-jacket',
    'Obsidian Runner Jacket',
    'Light-reactive shell cut for after-dark drops.',
    'A premium shell with reflective detailing, storm cuffs, and a tapered performance cut for night movement.',
    'Nova Lab',
    '@novalab',
    24800,
    'USD',
    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '6 hours',
    'After Hours Drop',
    array['outerwear', 'night-run', 'limited', 'jacket', 'running'],
    100
  ),
  (
    'gold-line-timepiece',
    'Gold Line Timepiece',
    'Satin black dial, champagne lume, 1-of-300.',
    'Machined steel casework with restrained gold detailing for collectors who want a luxury watch with drop energy.',
    'Aureate Goods',
    '@aureate',
    32500,
    'USD',
    'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '12 hours',
    'Collectors Window',
    array['watch', 'collectors', 'luxury', 'timepiece'],
    95
  ),
  (
    'pulse-audio-case',
    'Pulse Audio Case',
    'Carbon shell carry for premium listening kits.',
    'Compact shell case for headphones, cables, and creator audio setups with a velvet-lined interior.',
    'Echo Atelier',
    '@echoatelier',
    11800,
    'USD',
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '3 hours',
    'Flash Capsule',
    array['audio', 'accessory', 'flash-sale', 'headphones', 'music'],
    92
  ),
  (
    'noir-carry-duffel',
    'Noir Carry Duffel',
    'Soft-structured weekender with hidden utility grid.',
    'A minimal premium travel duffel with soft structure, internal organization, and refined carry hardware.',
    'Veil Works',
    '@veilworks',
    18900,
    'USD',
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '20 hours',
    'Weekend Reserve',
    array['travel', 'bag', 'minimal', 'duffel', 'weekender'],
    88
  ),
  (
    'ember-court-sneakers',
    'Ember Court Sneakers',
    'Low-profile leather runner with warm copper accents.',
    'Street-ready sneakers with premium leather panels, comfort foam, and subtle metallic hits for city rotation.',
    'District Assembly',
    '@districtassembly',
    21400,
    'USD',
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '15 hours',
    'Street Rotation',
    array['sneakers', 'footwear', 'runner', 'streetwear'],
    86
  ),
  (
    'atlas-pour-over-set',
    'Atlas Pour-Over Set',
    'Stoneware brew ritual kit for slow morning drops.',
    'A coffee setup with dripper, server, and textured cups designed for a premium home cafe moment.',
    'House Meridian',
    '@housemeridian',
    9800,
    'USD',
    'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '28 hours',
    'Morning Ritual',
    array['coffee', 'brew', 'pour-over', 'cafe', 'home'],
    84
  ),
  (
    'halo-desk-lamp',
    'Halo Desk Lamp',
    'Soft ambient beam built for focused night sessions.',
    'A compact desk lamp with dimmable warmth, studio-ready glow, and a minimal silhouette for workspaces.',
    'Still Form',
    '@stillform',
    13200,
    'USD',
    'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '18 hours',
    'Studio Focus',
    array['desk', 'workspace', 'lighting', 'minimal', 'studio'],
    82
  ),
  (
    'meridian-camera-sling',
    'Meridian Camera Sling',
    'Compact creator carry with padded lens bays.',
    'A travel sling for mirrorless kits, batteries, and creator essentials with weather-safe structure.',
    'Frame State',
    '@framestate',
    15600,
    'USD',
    'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '10 hours',
    'Creator Pack',
    array['camera', 'photography', 'bag', 'creator', 'travel'],
    80
  ),
  (
    'velvet-smoke-fragrance',
    'Velvet Smoke Fragrance',
    'Warm amber scent with suede, cedar, and dusk spice.',
    'A limited fragrance release with soft smoke, amber resin, and skin-close woods for evening wear.',
    'Quiet Archive',
    '@quietarchive',
    14200,
    'USD',
    'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '30 hours',
    'Evening Ritual',
    array['fragrance', 'perfume', 'luxury', 'evening'],
    78
  ),
  (
    'quarry-knit-overshirt',
    'Quarry Knit Overshirt',
    'Dense textured layer with a soft architectural drape.',
    'A premium knit overshirt that bridges tailoring and street layering with tactile structure.',
    'North Common',
    '@northcommon',
    17600,
    'USD',
    'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '22 hours',
    'Layer Study',
    array['knit', 'overshirt', 'outerwear', 'minimal', 'layering'],
    76
  ),
  (
    'onyx-espresso-grinder',
    'Onyx Espresso Grinder',
    'Precision burr workflow for premium home baristas.',
    'A compact espresso grinder tuned for cafe-style mornings, low retention, and tactile control.',
    'Ratio Studio',
    '@ratiostudio',
    26900,
    'USD',
    'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '26 hours',
    'Barista Lab',
    array['coffee', 'espresso', 'brew', 'kitchen', 'barista'],
    74
  ),
  (
    'signal-wireless-headphones',
    'Signal Wireless Headphones',
    'Studio-tuned over-ear sound with travel calm.',
    'Noise-controlled headphones with long battery life, balanced sound, and soft-touch materials for focused listening.',
    'Tone Bureau',
    '@tonebureau',
    22900,
    'USD',
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '16 hours',
    'Listening Room',
    array['audio', 'headphones', 'music', 'travel', 'studio'],
    72
  ),
  (
    'tidebreaker-sailing-shell',
    'Tidebreaker Sailing Shell',
    'Salt-ready outer layer built for wind, spray, and marina nights.',
    'A technical sea jacket with storm zip shielding, breathable lining, and a premium deck-ready silhouette.',
    'Harbor Division',
    '@harbordivision',
    23600,
    'USD',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '14 hours',
    'Blue Current',
    array['sea', 'sailing', 'jacket', 'coastal', 'outerwear'],
    70
  ),
  (
    'azure-deck-sandals',
    'Azure Deck Sandals',
    'Grip-soled sandals for hot piers and bright water days.',
    'Minimal premium sandals with fast-dry straps and soft foam support for sea trips and beach clubs.',
    'Shoreline Atelier',
    '@shorelineatelier',
    8400,
    'USD',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '19 hours',
    'Sun Pier',
    array['sea', 'sandals', 'beach', 'travel', 'summer'],
    68
  ),
  (
    'marina-weekend-tote',
    'Marina Weekend Tote',
    'Oversized carry-all for towels, sunscreen, and sea-day extras.',
    'A structured tote with coated canvas, internal bottle holders, and a soft coastal palette for boat and beach days.',
    'Coast Theory',
    '@coasttheory',
    12800,
    'USD',
    'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '24 hours',
    'Harbor Carry',
    array['sea', 'beach', 'tote', 'bag', 'weekend'],
    66
  ),
  (
    'reef-stripe-towel-set',
    'Reef Stripe Towel Set',
    'Heavy cotton towels with resort-weight softness.',
    'A premium towel bundle for sea escapes, with oversized weave, absorbent loops, and clean striped detailing.',
    'Tidal Home',
    '@tidalhome',
    7600,
    'USD',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '21 hours',
    'Cabana Stack',
    array['sea', 'towel', 'beach', 'resort', 'summer'],
    64
  ),
  (
    'coastline-snorkel-kit',
    'Coastline Snorkel Kit',
    'Clear-view mask and low-drag fins for bright-water mornings.',
    'A premium snorkel starter set with anti-fog lens treatment, travel mesh bag, and sea-ready comfort fit.',
    'Blue Arc',
    '@bluearc',
    15400,
    'USD',
    'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '32 hours',
    'Open Water',
    array['sea', 'snorkel', 'travel', 'water-sport', 'beach'],
    62
  ),
  (
    'ivory-vow-silk-shirt',
    'Ivory Vow Silk Shirt',
    'Soft-shine ceremony shirt cut for wedding light.',
    'A premium silk-blend shirt tailored for marriage celebrations, formal portraits, and clean tuxedo layering.',
    'Maison Thread',
    '@maisonthread',
    17200,
    'USD',
    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '17 hours',
    'Ceremony Edit',
    array['marriage', 'wedding', 'shirt', 'formal', 'ceremony'],
    60
  ),
  (
    'midnight-ceremony-blazer',
    'Midnight Ceremony Blazer',
    'Structured formal jacket with satin-edge restraint.',
    'A deep navy blazer made for marriage receptions and black-tie entrances, with sharp lines and soft movement.',
    'Blackroom Tailor',
    '@blackroomtailor',
    31400,
    'USD',
    'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '29 hours',
    'Reception Night',
    array['marriage', 'wedding', 'blazer', 'formal', 'luxury'],
    58
  ),
  (
    'champagne-veil-dress',
    'Champagne Veil Dress',
    'Fluid satin dress designed for elegant wedding movement.',
    'A refined occasion dress for marriage celebrations with soft drape, luminous fabric, and quiet statement energy.',
    'Velour Hall',
    '@velourhall',
    28600,
    'USD',
    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '34 hours',
    'Golden Aisle',
    array['marriage', 'wedding', 'dress', 'formal', 'occasion'],
    56
  ),
  (
    'pearl-evening-heels',
    'Pearl Evening Heels',
    'Satin heels with ceremony-friendly comfort and glow.',
    'Elegant formal heels designed for wedding looks, long receptions, and premium evening styling.',
    'Lune Atelier',
    '@luneatelier',
    19800,
    'USD',
    'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '23 hours',
    'Reception Steps',
    array['marriage', 'wedding', 'heels', 'formal', 'shoes'],
    54
  ),
  (
    'tailored-vow-trousers',
    'Tailored Vow Trousers',
    'Clean formal drape for marriage weekends and late receptions.',
    'Refined wool-blend trousers with a ceremonial silhouette and all-night comfort for wedding events.',
    'North Chapel',
    '@northchapel',
    16400,
    'USD',
    'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '27 hours',
    'Formal Line',
    array['marriage', 'wedding', 'trousers', 'formal', 'tailored'],
    52
  ),
  (
    'alloy-laptop-sleeve',
    'Alloy Laptop Sleeve',
    'Padded premium sleeve for daily carry and clean desk setups.',
    'A minimal laptop sleeve with soft lining, magnetic closure, and structured protection for portable work.',
    'Circuit House',
    '@circuithouse',
    9200,
    'USD',
    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '25 hours',
    'Work Carry',
    array['laptop', 'sleeve', 'tech', 'bag', 'workspace'],
    50
  ),
  (
    'vector-portable-monitor',
    'Vector Portable Monitor',
    'Slim second screen for travel editing and dual-screen focus.',
    'A premium portable monitor for laptop workflows, creators, and remote setup flexibility.',
    'Display Bureau',
    '@displaybureau',
    27900,
    'USD',
    'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '31 hours',
    'Dual View',
    array['laptop', 'monitor', 'tech', 'workspace', 'productivity'],
    48
  ),
  (
    'keystone-mechanical-keyboard',
    'Keystone Mechanical Keyboard',
    'Compact tactile board tuned for laptop-first desks.',
    'A premium wireless keyboard with crisp switches, compact footprint, and all-day typing comfort for laptop users.',
    'Input Standard',
    '@inputstandard',
    14300,
    'USD',
    'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '20 hours',
    'Typing Room',
    array['laptop', 'keyboard', 'tech', 'desk', 'workspace'],
    46
  ),
  (
    'dockline-usbc-hub',
    'Dockline USB-C Hub',
    'Desk dock that turns one laptop port into a full studio.',
    'A premium multi-port USB-C hub for laptop charging, display output, storage, and creator desk setups.',
    'Port Standard',
    '@portstandard',
    11200,
    'USD',
    'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '18 hours',
    'Port Stack',
    array['laptop', 'usb-c', 'hub', 'desk', 'tech'],
    44
  ),
  (
    'arc-travel-laptop-charger',
    'Arc Travel Laptop Charger',
    'High-output compact charger for laptops, phones, and airport days.',
    'A fast-charging GaN power brick built for laptop travel kits, shared charging, and light carry.',
    'Watt Form',
    '@wattform',
    9600,
    'USD',
    'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
    timezone('utc', now()) + interval '22 hours',
    'Power Lane',
    array['laptop', 'charger', 'travel', 'tech', 'power'],
    42
  )
on conflict (slug) do update
set
  title = excluded.title,
  tagline = excluded.tagline,
  description = excluded.description,
  seller_display_name = excluded.seller_display_name,
  seller_handle = excluded.seller_handle,
  price_cents = excluded.price_cents,
  currency_code = excluded.currency_code,
  hero_image_url = excluded.hero_image_url,
  sale_end_time = excluded.sale_end_time,
  drop_label = excluded.drop_label,
  tag_list = excluded.tag_list,
  sort_rank = excluded.sort_rank;

insert into public.product_media (product_id, media_url, media_type, position)
select id, hero_image_url, 'image', 0
from public.products
on conflict do nothing;

insert into public.inventory (product_id, available_count, total_count)
select
  products.id,
  inventory_seed.available_count,
  inventory_seed.total_count
from public.products
join (
  values
    ('obsidian-runner-jacket', 14, 60),
    ('gold-line-timepiece', 33, 300),
    ('pulse-audio-case', 8, 40),
    ('noir-carry-duffel', 21, 90),
    ('ember-court-sneakers', 17, 75),
    ('atlas-pour-over-set', 28, 110),
    ('halo-desk-lamp', 19, 80),
    ('meridian-camera-sling', 12, 45),
    ('velvet-smoke-fragrance', 26, 140),
    ('quarry-knit-overshirt', 16, 70),
    ('onyx-espresso-grinder', 9, 35),
    ('signal-wireless-headphones', 22, 95),
    ('tidebreaker-sailing-shell', 18, 70),
    ('azure-deck-sandals', 30, 140),
    ('marina-weekend-tote', 24, 90),
    ('reef-stripe-towel-set', 36, 180),
    ('coastline-snorkel-kit', 15, 60),
    ('ivory-vow-silk-shirt', 14, 55),
    ('midnight-ceremony-blazer', 11, 40),
    ('champagne-veil-dress', 9, 32),
    ('pearl-evening-heels', 13, 48),
    ('tailored-vow-trousers', 16, 64),
    ('alloy-laptop-sleeve', 28, 120),
    ('vector-portable-monitor', 10, 38),
    ('keystone-mechanical-keyboard', 21, 88),
    ('dockline-usbc-hub', 26, 96),
    ('arc-travel-laptop-charger', 34, 150)
) as inventory_seed(slug, available_count, total_count)
  on inventory_seed.slug = products.slug
on conflict (product_id) do update
set
  available_count = excluded.available_count,
  total_count = excluded.total_count,
  updated_at = timezone('utc', now());

update public.products
set sale_end_time = null
where slug not in (
  'obsidian-runner-jacket',
  'pulse-audio-case',
  'tidebreaker-sailing-shell',
  'midnight-ceremony-blazer',
  'vector-portable-monitor'
);
